"""Add version column to Document model

Revision ID: 214a9efd7c1f
Revises: b68b89c342cd
Create Date: 2024-05-14 21:44:06.250198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214a9efd7c1f'
down_revision = 'b68b89c342cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
