"""Remove file_path and add file_data column

Revision ID: b68b89c342cd
Revises: 6a855f126baa
Create Date: 2024-04-25 14:40:56.089921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68b89c342cd'
down_revision = '6a855f126baa'
branch_labels = None
depends_on = None


def upgrade():
    # Clear existing data in the Document table
    op.execute("DELETE FROM document")
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('file_data')

    # ### end Alembic commands ###
